name: Integration Tests

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - "*"

jobs:
  Integration:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: "recursive"
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Cache .pyprojectx
        uses: actions/cache@v2
        with:
          path: .pyprojectx
          key: ${{ runner.os }}-pyprojectx
      - name: Run tests
        run: python pw i && python pw test
